### ISSUE TITLE
我想问一下关于 BanGround Player 里的判定调节问题

### ISSUE THREAD

**Issue by shiawasenahikari** [BanGround/BanGround-Player#24]
我把我自己在 Bestdori 上写的自制谱放到 BanGround Player 里玩时，发现 note 比 BGM 快了 0.1 秒左右（在 Bestdori 上预览时 note 是和 BGM 吻合的）。

然后我试着打开设置来调整判定，发现设置里有两个选项，判定偏移（Judge Offset）和视觉偏移（Visual Offset），但我不论调整其中哪一个数值，而且即使把这些数值调整得很夸张（-10000），实际玩的过程中 note 的位置仍和最开始的状态一模一样，也就是判定根本没有被调节。

请问我应该怎么操作才能偏移 note 的位置使得它们跟 BGM 吻合上呢？谢谢！

我是用 iPad 自带的 Safari 浏览器玩的，系统是 iPadOS 13.4.1。

**Comment by zz5840** [comment]
是bug 懒得修 请留下您的邮箱以参与内测

**Comment by shiawasenahikari** [comment]
smallyang0613@qq.com 感谢
